name: flutter_prixz
description: "Prueba tecnica PRIXZ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  app_bar_with_search_switch: ^1.8.5
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.18.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  responsive_grid: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
